name: Release Bot

on:
  pull_request:
    types: [opened, reopened, closed]
    branches: [main, stable]
  release:
    types: [released, prereleased]

jobs:
  run:
    timeout-minutes: 10
    if: startsWith(github.head_ref, 'releases/') || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          client-id: ${{ secrets.OAI_GITHUB_APP_ID }}
          private-key: ${{ secrets.OAI_GITHUB_APP_PRIVATE_KEY }}
          owner: openai
          repositories: statsig-publish-sdk-action
      - uses: openai/statsig-publish-sdk-action@main
        with:
          kong-private-key: ${{ secrets.KONG_GH_APP_PRIVATE_KEY }}
