name: instrumented testbed

on:
  push:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/testbed-tests.yml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/testbed-tests.yml

jobs:
  gradle:
    strategy:
      matrix:
        api-level: [19]
        target: [default]
    runs-on: macos-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: checkout
        uses: actions/checkout@v2

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Build SDK to Maven Local
        run: ./gradlew publishToMavenLocal

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script:  cd androidsdktestbed && STATSIG_CLIENT_KEY=$STATSIG_CLIENT_KEY ./gradlew connectedCheck
        env:
          STATSIG_CLIENT_KEY: ${{ secrets.ANDROID_SDK_E2E_CLIENT_KEY }}